# Generated by Django 3.1.7 on 2021-02-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='section_title',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
